apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: test-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: node:14 # Update with your image
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: "mongodb://admin:secret@mongodb:27017/mydb"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  namespace: test-namespace
spec:
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
