version: '3.8'

services:
  web:
    build: .  # Build from the root-level Dockerfile
    container_name: web
    ports:
      - "8085:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://admin:secret@mongodb:27017/mydb"
    networks:
      - app_network

  mongodb:
    build: ./mongodb  # Build from the custom MongoDB Dockerfile in the 'mongodb' directory
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


    networks:
      - app_network


volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
