version: '3.8'

services:
  web:
    build: .
    ports:
      - "8085:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://mongodb:27017/mydb"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

