version: '3.8'

services:
  web:
    build:
      context: .  # Build from the root-level Dockerfile
    container_name: nodejs
    ports:
      - "8085:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://admin:secret@mongodb:27017/mydb"
    networks:
      - app_network

  mongodb:
    build:
      context: ./mongodb  # Build from the custom MongoDB Dockerfile in the 'mongodb' directory
      args:
        MONGO_ROOT_PASSWORD: secret  # Pass the build-time argument for MongoDB password
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:
    name: webMongo

networks:
  app_network:
    driver: bridge
