pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '5')) // Keep only the last 5 builds
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/AshokTippaluri/ashok-test.git'
            }
        }
        
        stage('Cleanup Docker') {
            steps {
                script {
                    sh 'docker image prune -a -f'
                    sh 'docker system prune -a -f --volumes'
                }
            }
        }
        
        stage('Run Containers') {
            steps {
                script {
                    sh 'docker compose -f docker-compose.yaml up -d'
                    sh 'sleep 20'
                }
            }
        }

        stage('Health Check') {
            steps {
                script {
                    sh 'curl -f http://localhost:8085/items || exit 1'
                }
            }
        }

        stage('Container Connectivity Check') {
            steps {
                script {
                    // Check if the web container can reach MongoDB internally
                    sh 'docker exec web ping -c 4 mongodb'
                    // Alternatively, test MongoDB connection from within the web container
                    sh 'docker exec web curl -f mongodb:27017 || echo "MongoDB connection failed"'
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    sh 'docker compose -f docker-compose.yaml down -v'
                }
            }
        }
    }
}
