apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashok
  name: ashok
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ashok
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashok
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
